### PR TITLE
qsv: fixed qsv pipeline

### PR DESCRIPTION
**Pull request by galinart**
Hi @galad87,

I have validated the QSV pipeline and made some fixes required for video memory on Windows.

### CODE REVIEW

**Comment by galad87** [comment]
Thanks, unfortunately my original pull request has some conflicts, I'll try to rebase it.

**Comment by galinart** [comment]
Yes, conflicts are more related to your source code changes and I decided to leave it for you as you know better.

**Comment by galad87** [comment]
I rebased https://github.com/HandBrake/HandBrake/pull/3473 , and added a check in pix_fmt_is_supported() to use a biplanar format only if hardware decoding is enabled. I think it should check if the qsv hardware decoder is enabled in the job too, but I don't have any qsv hardware to test.

Anyway, if you can rebase your changes and test them on some actual hardware, or probably it would be better to give you access to this fork so you can push them.

**Comment by galinart** [comment]
@galad87 I have already validated the QSV configurations and it works correctly in this branch. 
you did not add my changes into the https://github.com/HandBrake/HandBrake/pull/3473 . 
https://github.com/HandBrake/HandBrake/pull/3473/commits/998fe6f849a18a04517aa1597881b9cf219f1fe9#diff-51673e318087695f09e0730fcfc124ba22910f3dcc1a036bc3ec1c454d726d68R5886 is incorrect cause AV_PIX_FMT_P010LE and AV_PIX_FMT_NV12 are only needed if both QSV decoder and QSV encoder are used and my changes include this. 

Let me know if anything is required from my side.

**Pull request closed without merging**
